### ISSUE TITLE
setup project structure using latest cmake-init

### ISSUE THREAD

**Issue by cgcostume** [cginternals/openll-asset-generator#1]
Use latest cmake-init as base project structure/setup. Since we will probably have a cli, a lib, as well as a service, we could use a setup similar to [glraw](https://github.com/cginternals/glraw):
```
source/llassetgen-cmd (c++ command line interface)
source/llassetgen (c++ lib)
source/llassetgen-client (typescript based web client?)
source/llassetgen-server (node based server?)
```

**Comment by Lichtso** [comment]
https://github.com/cginternals/cmake-init

**Comment by Lichtso** [comment]
I setup all C++ targets (lib, cmd, tests) the other two (server and client) will have to be done later when their build process becomes more clear if there is any.
