### ISSUE TITLE
plan and discuss web-service capabilities

### ISSUE THREAD

**Issue by cgcostume** [cginternals/openll-asset-generator#12]
This issue should be used to plan and discuss the capabilities of an openll asset generation service.

**Comment by cgcostume** [comment]
Rendering implementations for c++ or webgl etc. should always be implemented and maintained in [cginternals/openll](https://github.com/cginternals/openll).

**Comment by cgcostume** [comment]
we should consider https://electron.atom.io/ as a framework for future web-services

**Comment by cgcostume** [comment]
[Announcing TypeScript support in Electron](https://electron.atom.io/blog/2017/06/01/typescript)

**Comment by anne-gropler** [comment]
This issue is postponed. For GUI and rendering we use QT for now.
