### ISSUE TITLE
gather and enlist latest/state-of-the-art signed distance transform algorithms and resources

### ISSUE THREAD

**Issue by cgcostume** [cginternals/openll-asset-generator#2]
This issue should be used to gather and discuss various resources for signed distance transforms. All algorithms that will be implemented in llassetgen should probably be referenced in the readme.

**Comment by cgcostume** [comment]
distance transform and packing implementation [glorp/fontbaker](https://github.com/zorbathut/glorp/blob/4307a13af75ca1c5386988b1b693c5d97a4c3a94/fontbaker/main.cpp) - didn't review

**Comment by cgcostume** [comment]
[Parallel Banding Algorithm to Compute Exact Distance Transform with the GPU](http://www.comp.nus.edu.sg/~tants/pba.html), Thanh-Tung Cao, Ke Tang, Anis Mohamed, and Tiow-Seng Tan, 2010 - We have a GPU implementation somewhere, please ask if required.

**Comment by cgcostume** [comment]
[The "dead reckoning" signed distance transform](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.102.7988&rep=rep1&type=pdf), George J. Grevera, 2004 - I should have a basic implementation somewhere, please ask if required.

**Comment by cgcostume** [comment]
[Distance Transform Algorithms and their Implementation and Evaluation](https://www.springer.com/cda/content/document/cda_downloaddocument/9780387312019-c1.pdf), George J. Grevera

**Comment by Lichtso** [comment]
[Distance Transforms of Sampled Functions](http://cs.brown.edu/~pff/papers/dt-final.pdf), Pedro F. Felzenszwalb and Daniel P. Huttenlocher (2012)
