### ISSUE TITLE
gather and enlist latest/state-of-the-art texture atlas packing algorithms and resources

### ISSUE THREAD

**Issue by cgcostume** [cginternals/openll-asset-generator#3]
This issue should be used to gather and discuss various resources for texture atlas packing algorithms (bin packing). All algorithms that will be implemented in llassetgen should probably be referenced in the readme.

**Comment by cgcostume** [comment]
distance transform and packing implementation [glorp/fontbaker](https://github.com/zorbathut/glorp/blob/4307a13af75ca1c5386988b1b693c5d97a4c3a94/fontbaker/main.cpp) - didn't review

**Comment by cgcostume** [comment]
* [intel-ipp](https://software.intel.com/en-us/intel-ipp)
* [eigen](https://bitbucket.org/eigen/eigen/)

**Comment by Felerius** [comment]
[A Thousand Ways to Pack the Bin](http://clb.demon.fi/files/RectangleBinPack.pdf) compares 4 basic texture packing algorithms with several different heuristics resulting in 2619 variants being compared and scored. Results include both the best, slowest algorithms as well as more efficient variants.
