### ISSUE TITLE
Integrate further changes from cginternals/cmake-init#78

### ISSUE THREAD

**Issue by Felerius** [cginternals/openll-asset-generator#34]

**Comment by anne-gropler** [comment]
@Felerius Is this done yet? It seems like it. If so, please close this issue.

**Comment by Felerius** [comment]
It was fixed in that PR, but I don't think we have integrated those into our repo yet (they had just been merged when you asked). I can make another PR updating our version of cmake-init today or tomorrow to fix this.

**Comment by anne-gropler** [comment]
Ok. I remember that I integrated some changes into our repo, but I am not sure if I did it completely.

**Comment by Felerius** [comment]
Fixed by #39
