### ISSUE TITLE
Parallelize distance field creation

### ISSUE THREAD

**Issue by Blaidd-Drwg** [cginternals/openll-asset-generator#64]
With 90% of CPU time, the biggest bottleneck so far is the computation of the distance fields. By generating multiple distance fields in parallel with OpenMP we can achieve a significant speedup

Some work has already been done, see #59. So far, these changes have roughly halved the runtime on Linux, however they have not been tested on MacOS and Windows yet.
Also, the Travis tests for Clang on Linux currently fail because of travis-ci/travis-ci#8613.

**Comment by anne-gropler** [comment]
Tested on Windows. It works and performance seems better (didn't run a benchmark, so I don't have any numbers).

**Comment by anne-gropler** [comment]
Travis issue is fixed in PR #69
