### ISSUE TITLE
space char

### ISSUE THREAD

**Issue by anne-gropler** [cginternals/openll-asset-generator#66]
The space char currently is not part of the atlas nor the fnt-file. When the space char is part of a char preset, the error "Error: glyph with code 32 could not be rendered" is thrown.

This will also be a problem for all spacing characters, such as tab.

A spacing character has currently no preserved space in the atlas. Two possible solutions:
1) Have a preserved empty/black space in the atlas that has the width (and height?) of the space char.
2) Have a 1x1 space (one pixel) in the atlas and only the fnt-file having the width value of the space char.

**Comment by scheibel** [comment]
I prefer solution 2. I assume the pixel will have to be handled during atlas layouting as well.
